### ISSUE TITLE
Any plan to support Carthage?

### ISSUE THREAD

**Issue by tylerlong** [kylef/Stencil#27] opened 2015-09-26 13:56 UTC
https://github.com/Carthage/Carthage

I think it is easy: https://github.com/Carthage/Carthage#share-your-xcode-schemes

**Comment by kylef** [comment] 2015-09-26 17:24
The schemes are already shared, do you happen to know what else is needed to make this work with Carthage?

**Comment by esttorhe** [comment] 2015-09-26 17:50
I just tried this on my computer with the following `Cartfile`:
```swift
github "kylef/stencil"
```

And `carthage bootstrap` gives the following output:
```console
*** No Cartfile.resolved found, updating dependencies
*** Cloning Stencil
*** Checking out Stencil at "0.3.0"
*** xcodebuild output can be found in /var/folders/xk/378q_x1x4b3289cbr_kjyhzr0000gn/T/carthage-xcodebuild.sj20gi.log
*** Building scheme "Stencil" in Stencil.xcworkspace
…… <Redacted output for brevity>……
PhaseScriptExecution Copy\ Pods\ Resources /Users/<username>/Library/Developer/Xcode/DerivedData/Stencil-berzxjjyqkvunscewwpcieqtncuu/Build/Intermediates/Stencil.build/Release/StencilTests.build/Script-36A8E92EBDE6D917075028D4.sh
(33 failures)
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
…… <Redacted output>
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
/Users/<username>/Downloads/Carthage/Checkouts/Stencil/Stencil/TemplateLoader/Include.swift:2:8: error: no such module 'PathKit'
```

The issue is that the `podspec` manages the dependency of `PathKit` while `Carthage` is unable to; easiest way would be to actually rely con `CocoaPods` ability to support `Carthage` via uploading the `Pods` folder and the `_Pods.xcworkspace` symlink that's generated.

I did that with [`RxViewModel`](https://github.com/esttorhe/RxViewModel) but my project is structured differently because I used the template that lays everything out for me but is a good way to start looking at

**Comment by tylerlong** [comment] 2015-09-27 08:53
@kylef I just started using Carthage and I don't have much experience. I have no hands-on experiece to make a library Carthage compatible.

I chose another swift template library: https://github.com/groue/GRMustache.swift  It supports Carthage. Maybe you can check its source code?

**Comment by cezheng** [comment] 2015-10-07 13:11
@kylef 
This repo happens to have some pod dependencies, but the Pod folder is not added to the repo. Carthage won't `pod install` for the user so I guess all you need to do is to add & commit the `Pod` folder.

**Comment by Danappelxx** [comment] 2015-11-03 04:39
I guess this can be closed now that you've completely switched over to conche?

**Comment by tylerlong** [comment] 2015-11-03 10:24
Feel free to close it. I am not using this library currently. Myself have created several libraries(simple ones) which support Carthage. I cannot see the reason why does this library no Carthage support.

**Comment by Danappelxx** [comment] 2015-11-03 15:57
@tylerlong it's a shame (I prefer Carthage, too) but the reason it doesn't work is because @kylef no longer uses Xcode, and the way Carthage works is by simply building an Xcode project.

Right now the best alternative to Carthage is Cocoapods Rome, a plugin for cocoapods which spits out frameworks instead of creating a linked Xcode project.

**Comment by kylef** [comment] 2015-11-03 18:51
I have full intentions of adding Carthage support soon via [pre-build frameworks](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) on GitHub releases. So won't close this just yet.

**Comment by Danappelxx** [comment] 2015-11-20 07:45
@kylef Any day now :clock1: :)

**Comment by njdehoog** [comment] 2015-11-23 10:51
Would it be a terrible idea to just include an Xcode project? It would make things simpler for us mere mortals who use Xcode ;)

**Comment by basememara** [comment] 2016-05-02 21:56
I created a PR for Carthage support #65 :tada:

**Comment by tkrajacic** [comment] 2016-10-17 07:11
@kylef Is there anything we can help here to get this along?

**Closed** 2016-12-01 18:26 UTC
Labels: question

**Comment by kylef** [comment] 2016-12-01 18:28
You can find instructions on using this library with Carthage at https://stencil.fuller.li/en/latest/installation.html#carthage.
