### ISSUE TITLE
Use of undeclared type 'Float80'

### ISSUE THREAD

**Issue by ErastP** [kylef/Stencil#81] opened 2016-12-12 07:32 UTC
I am using xcode 8 and get errors about the unsupported type Float80. I found out that Float80 is an architecture dependent type, which is not available for ARM-based platforms. I am developing for iOS. Please check.

**Comment by AliSoftware** [comment] 2016-12-12 11:51
This is a duplicate of #76, which has already been fixed in `master`

(@kylef maybe you should add a CHANGELOG entry to mention that fix, I don't see it in the current CHANGELOG)

**Comment by kylef** [comment] 2016-12-12 18:58
Yes that's right, this was fixed in master. I've added a changelog entry in 39517b7. If you're targeting iOS I'd recommend sticking to Stencil 0.6 for now. I hope to get a new release out shortly.

**Closed by kylef** 2016-12-12 18:58 UTC
